import tkinter as tk
import customtkinter as ctk
from CreateCharacterClass import CharacterCreator

ctk.set_appearance_mode("Light")


class StatEntryFrame(tk.Frame):
    def __init__(self, master=None):
        super().__init__(master)
        # allowing the new frame to have a CTk obj as a master
        self.master = master
        # declaring fonts
        self.font = ctk.CTkFont(family="Rockwell", size=14)
        self.special_font = ctk.CTkFont(family="Rockwell", size=18)
        self.header_font = ctk.CTkFont(family="Rockwell", size=28)
        # labels
        self.test = ctk.CTkLabel(self, font=self.font, text="Testing")
        self.test.pack()

        self.NameLabel = ctk.CTkLabel(self, font=self.font, text="Character Name")
        self.ClassLabel = ctk.CTkLabel(self, font=self.font, text="Class")
        self.LevelLabel = ctk.CTkLabel(self, font=self.font, text="Level")
        self.RaceLabel = ctk.CTkLabel(self, font=self.font, text="Race")
        self.BackgroundLabel = ctk.CTkLabel(self, font=self.font, text="Background")
        self.AlignmentLabel = ctk.CTkLabel(self, font=self.font, text="Alignment")
        self.PersonalityLabel = ctk.CTkLabel(self, font=self.font, text="Personality")
        self.IdealsLabel = ctk.CTkLabel(self, font=self.font, text="Ideals")
        self.BondsLabel = ctk.CTkLabel(self, font=self.font, text="Bonds")
        self.FlawsLabel = ctk.CTkLabel(self, font=self.font, text="Flaws")
        self.FeaturesLabel = ctk.CTkLabel(self, font=self.font, text="Features")
        self.TraitsLabel = ctk.CTkLabel(self, font=self.font, text="Traits")
        self.EquipmentLabel = ctk.CTkLabel(self, font=self.font, text="Equipment")
        self.Attack1Label = ctk.CTkLabel(self, font=self.font, text="Attack 1")
        self.Attack2Label = ctk.CTkLabel(self, font=self.font, text="Attack 2")
        self.Attack3Label = ctk.CTkLabel(self, font=self.font, text="Attack 3")
        self.STRLabel = ctk.CTkLabel(self, font=self.font, text="STR")
        self.STRBonusLabel = ctk.CTkLabel(self, font=self.font, text="")
        self.DEXLabel = ctk.CTkLabel(self, font=self.font, text="STR")
        self.DEXBonusLabel = ctk.CTkLabel(self, font=self.font, text="")
        self.CONLabel = ctk.CTkLabel(self, font=self.font, text="STR")
        self.CONBonusLabel = ctk.CTkLabel(self, font=self.font, text="")
        self.INTLabel = ctk.CTkLabel(self, font=self.font, text="STR")
        self.INTBonusLabel = ctk.CTkLabel(self, font=self.font, text="")
        self.WISLabel = ctk.CTkLabel(self, font=self.font, text="STR")
        self.WISBonusLabel = ctk.CTkLabel(self, font=self.font, text="")
        self.CHALabel = ctk.CTkLabel(self, font=self.font, text="STR")
        self.CHABonusLabel = ctk.CTkLabel(self, font=self.font, text="")
        self.PassivePerceptionLabel = ctk.CTkLabel(self, font=self.font, text="Passive Wisdom (Perception)")
        self.ACLabel = ctk.CTkLabel(self, font=self.font, text="Armor Class")
        self.SpeedLabel = ctk.CTkLabel(self, font=self.font, text="Speed")
        self.ProfBonusLabel = ctk.CTkLabel(self, font=self.font, text="Proficiency Bonus")
        self.HPMAXLabel = ctk.CTkLabel(self, font=self.font, text="Maximum HP")
        self.HPCURRLabel = ctk.CTkLabel(self, font=self.font, text="Current HP")
        self.HPTEMPLabel = ctk.CTkLabel(self, font=self.font, text="Temporary HP")
        self.HDTOTLabel = ctk.CTkLabel(self, font=self.font, text="Total Hit Dice")
        self.HDCURRLabel = ctk.CTkLabel(self, font=self.font, text="Current Hit Dice")
        self.ElectrumLabel = ctk.CTkLabel(self, font=self.font, text="EP")
        self.SilverLabel = ctk.CTkLabel(self, font=self.font, text="SP")
        self.GoldLabel = ctk.CTkLabel(self, font=self.font, text="GP")
        self.PlatinumLabel = ctk.CTkLabel(self, font=self.font, text="PP")
        self.CopperLabel = ctk.CTkLabel(self, font=self.font, text="CP")
        self.DeathSavesLabel = ctk.CTkLabel(self, font=self.font, text="Death Saves")
        self.SkillsLabel = ctk.CTkLabel(self, font=self.font, text="Skills")
        self.AthleticsLabel = ctk.CTkLabel(self, font=self.font, text="Athletics")
        self.AcrobaticsLabel = ctk.CTkLabel(self, font=self.font, text="Acrobatics")
        self.SOFLabel = ctk.CTkLabel(self, font=self.font, text="Slight of Hand")
        self.StealthLabel = ctk.CTkLabel(self, font=self.font, text="Stealth")
        self.ArcanaLabel = ctk.CTkLabel(self, font=self.font, text="Arcana")
        self.HistoryLabel = ctk.CTkLabel(self, font=self.font, text="History")
        self.InvestigationLabel = ctk.CTkLabel(self, font=self.font, text="Investigation")
        self.NatureLabel = ctk.CTkLabel(self, font=self.font, text="Nature")
        self.ReligionLabel = ctk.CTkLabel(self, font=self.font, text="Religion")
        self.AHLabel = ctk.CTkLabel(self, font=self.font, text="Animal Handling")
        self.InsightLabel = ctk.CTkLabel(self, font=self.font, text="Insight")
        self.MedicineLabel = ctk.CTkLabel(self, font=self.font, text="Medicine")
        self.PerceptionLabel = ctk.CTkLabel(self, font=self.font, text="Perception")
        self.SurvivalLabel = ctk.CTkLabel(self, font=self.font, text="Survival")
        self.DeceptionLabel = ctk.CTkLabel(self, font=self.font, text="Deception")
        self.IntimidationLabel = ctk.CTkLabel(self, font=self.font, text="Intimidation")
        self.PerformanceLabel = ctk.CTkLabel(self, font=self.font, text="Performance")
        self.PersuasionLabel = ctk.CTkLabel(self, font=self.font, text="Persuasion")
        self.InspirationLabel = ctk.CTkLabel(self, font=self.font, text="Inspiration")
        self.InitiativeLabel = ctk.CTkLabel(self, font=self.font, text="Initiative")
        self.SavingThrowsLabel = ctk.CTkLabel(self, font=self.font, text="Saving Throws")
        self.Str_St_Label = ctk.CTkLabel(self, font=self.font, text="Strength")
        self.Dex_St_Label = ctk.CTkLabel(self, font=self.font, text="Dexterity")
        self.Con_St_Label = ctk.CTkLabel(self, font=self.font, text="Constitution")
        self.Int_St_Label = ctk.CTkLabel(self, font=self.font, text="Intelligence")
        self.Wis_St_Label = ctk.CTkLabel(self, font=self.font, text="Wisdom")
        self.Cha_St_Label = ctk.CTkLabel(self, font=self.font, text="Charisma+")

        # kinter variables
        self.NameVar = ctk.StringVar(value="")
        self.ClassVar = ctk.StringVar(value="")
        self.LevelVar = ctk.IntVar(value=1)
        self.RaceVar = ctk.StringVar(value="")
        self.BackgroundVar = ctk.StringVar(value="")
        self.AlignmentVar = ctk.StringVar(value="")
        self.PersonalityVar = ctk.StringVar(value="")
        self.IdealsVar = ctk.StringVar(value="")
        self.BondsVar = ctk.StringVar(value="")
        self.FlawsVar = ctk.StringVar(value="")
        self.FeaturesVar = ctk.StringVar(value="")
        self.TraitsVar = ctk.StringVar(value="")
        self.EquipmentVar = ctk.StringVar(value="")
        self.Attack1Var = ctk.StringVar(value="")
        self.Attack2Var = ctk.StringVar(value="")
        self.Attack3Var = ctk.StringVar(value="")
        self.STRVar = ctk.IntVar(value=10)
        self.CONVar = ctk.IntVar(value=10)
        self.DEXVar = ctk.IntVar(value=10)
        self.INTVar = ctk.IntVar(value=10)
        self.WISVar = ctk.IntVar(value=10)
        self.CHAVar = ctk.IntVar(value=10)
        self.ACVar = ctk.StringVar(value="")
        self.SpeedVar = ctk.StringVar(value="0ft")
        self.ProfBonusVar = ctk.StringVar(value="")
        self.HPMaxVar = ctk.IntVar(value=0)
        self.HPCurrVar = ctk.IntVar(value=0)
        self.HPTempVar = ctk.IntVar(value=0)
        self.HDTotVar = ctk.IntVar(value=0)
        self.HDCurrVar = ctk.IntVar(value=0)


        # entry widgets
        self.NameEntry = ctk.CTkEntry(self, font=self.font, textvariable=self.NameVar)
        self.ClassEntry = ctk.CTkEntry(self, font=self.font, textvariable=self.ClassVar)
        self.LevelEntry = ctk.CTkEntry(self, font=self.font, textvariable=self.LevelVar)
        self.RaceEntry = ctk.CTkEntry(self, font=self.font, textvariable=self.RaceVar)
        self.BackgroundEntry = ctk.CTkEntry(self, font=self.font, textvariable=self.RaceVar)
        self.AlignmentEntry = ctk.CTkEntry(self, font=self.font, textvariable=self.RaceVar)


        # placing attributes on the frame


if __name__ == '__main__':
    test = ctk.CTk()
    frame = StatEntryFrame(master=test)
    test.geometry("1422x603")
    test.iconbitmap("dice-icon.ico")
    test.title("DND App")
    frame.pack(fill=ctk.BOTH, expand=True)

    test.mainloop()
